export const MENU_ITEMS = {
  ADD_TASK: 'ADD NEW TASK',
  TASK_LISTS: 'TASK LISTS',
  ANALYTICS_REPORT: 'ANALYTICS REPORT',
  RING_TONE: 'RING TONE',
};

export const INITIAL_TIME_LENGTH = {
  WORK: 25 * 60,
  break: 5 * 60,
};
